#!/usr/bin/env bash
# Camunda 8.9 — k3s + Helm + Elasticsearch + Identity/Keycloak
# Access via LoadBalancer IP directly (no ingress/domain needed)
# Login: demo / demo
set -euo pipefail

GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; NC='\033[0m'
info()  { echo -e "${GREEN}[✓]${NC} $*"; }
step()  { echo -e "\n${YELLOW}━━━ $* ━━━${NC}"; }
error() { echo -e "${RED}[✗] $*${NC}" >&2; exit 1; }
warn()  { echo -e "${YELLOW}[!]${NC} $*"; }

DEPLOY_DIR="$HOME/camunda-deploy"
SERVER_IP=$(hostname -I | awk '{print $1}')

# Internal service passwords (not exposed to Camunda users)
# openssl avoids tr/dd SIGPIPE issues under set -euo pipefail
_rand() { openssl rand -hex 32 2>/dev/null | head -c "$1"; }
KC_ADMIN_PASS="KcAdmin$(_rand 12)"
PG_PASS="Pg$(_rand 14)"
OIDC_SECRET="Oidc$(_rand 18)"

mkdir -p "$DEPLOY_DIR"
chmod 700 "$DEPLOY_DIR"
cat > "$DEPLOY_DIR/passwords.txt" << EOF
# Generated by camunda-k3s-setup.sh — DO NOT COMMIT
# Camunda login: demo / demo
KC_ADMIN_PASS=${KC_ADMIN_PASS}
PG_PASS=${PG_PASS}
OIDC_SECRET=${OIDC_SECRET}
SERVER_IP=${SERVER_IP}
EOF
chmod 600 "$DEPLOY_DIR/passwords.txt"

echo ""
echo -e "${GREEN}━━━ Camunda 8.9 Setup ━━━${NC}"
echo "  Server IP:  ${SERVER_IP}"
echo "  Login:      demo / demo"
echo ""

# ── System update ──────────────────────────────────────────────────────────────
step "System update"
sudo apt-get update -qq && sudo apt-get upgrade -y -qq || error "System update failed"
info "Done"

# ── k3s ───────────────────────────────────────────────────────────────────────
step "k3s"
if command -v k3s &>/dev/null; then
    info "Already installed, skipping"
else
    # k3s download can be slow — run directly (no background+spinner to avoid SIGPIPE)
    curl -sfL https://get.k3s.io | sh - || error "k3s install failed"
    info "Installed"
fi

mkdir -p ~/.kube
sudo cp /etc/rancher/k3s/k3s.yaml ~/.kube/config
sudo chown "$(id -u):$(id -g)" ~/.kube/config
chmod 600 ~/.kube/config
export KUBECONFIG=~/.kube/config
grep -q 'KUBECONFIG' ~/.bashrc || echo 'export KUBECONFIG=~/.kube/config' >> ~/.bashrc

info "Waiting for node Ready..."
until kubectl get nodes 2>/dev/null | grep -qE '\bReady\b'; do sleep 2; done
kubectl wait --for=condition=Ready node --all --timeout=120s
info "Node Ready"

# ── Helm ──────────────────────────────────────────────────────────────────────
step "Helm"
if command -v helm &>/dev/null; then
    info "Already installed, skipping"
else
    curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash >/dev/null 2>&1 \
        || error "Helm install failed"
    info "Installed"
fi

# ── Helm repos ────────────────────────────────────────────────────────────────
step "Helm repos"
helm repo add camunda https://helm.camunda.io 2>/dev/null || true
helm repo update || error "Helm repo update failed"
info "Done"

# ── Namespace ─────────────────────────────────────────────────────────────────
step "Namespace"
kubectl create namespace camunda --dry-run=client -o yaml | kubectl apply -f -
info "Done"

# ── Camunda Helm values ────────────────────────────────────────────────────────
step "Camunda Helm values"

# Keycloak auth URLs (internal cluster URL for backend, IP for browser redirects)
# The HTTP port is the nodePort of the LoadBalancer service (set after first install,
# but we use the standard 8080 for templating — actual port is shown at the end)
KEYCLOAK_INTERNAL="http://camunda-keycloak/auth"

cat > "$DEPLOY_DIR/values-camunda.yaml" << HELMEOF
global:
  identity:
    auth:
      enabled: true
      # publicIssuerUrl: set after first install via helm upgrade once we know the nodePort
      # redirectUrl: set after first install via helm upgrade once we know the nodePort

  security:
    authentication:
      method: oidc     # REQUIRED — without this Zeebe uses basic auth and Connectors fail

  postgresql:
    auth:
      password: "${PG_PASS}"

orchestration:
  enabled: true
  replicaCount: 1
  clusterSize: "1"
  partitionCount: "1"
  replicationFactor: "1"
  affinity:
    podAntiAffinity: {}    # required for single-node k8s

  exporters:
    camunda:
      enabled: true        # Elasticsearch exporter (Operate/Tasklist)
    rdbms:
      enabled: false

  data:
    secondaryStorage:
      type: elasticsearch

  resources:
    requests:
      memory: "1Gi"
      cpu: "500m"
    limits:
      memory: "2Gi"
      cpu: "2000m"

  service:
    type: LoadBalancer     # k3s assigns external IP from server
    headless:
      type: ClusterIP

  security:
    authentication:
      oidc:
        secret:
          inlineSecret: "${OIDC_SECRET}"
        # redirectUrl: set below after first install

connectors:
  enabled: true
  inbound:
    mode: polling

  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"

  security:
    authentication:
      oidc:
        secret:
          inlineSecret: "${OIDC_SECRET}"

  env:
    # Explicit gRPC auth — chart sets AUTH_TYPE=KEYCLOAK but not CLIENT_ID/SECRET
    # without these Connectors get UNAUTHENTICATED on gRPC calls to Zeebe
    - name: CAMUNDA_CLIENT_ID
      value: "connectors"
    - name: CAMUNDA_CLIENT_SECRET
      value: "${OIDC_SECRET}"
    - name: CAMUNDA_AUTH_SERVER_URL
      value: "${KEYCLOAK_INTERNAL}/realms/camunda-platform"
    - name: ZEEBE_CLIENT_SECURITY_PLAINTEXT
      value: "true"

elasticsearch:
  enabled: true
  master:
    masterOnly: false
    replicaCount: 1
    heapSize: 1g
    persistence:
      size: 15Gi
    resources:
      requests:
        memory: "2Gi"
        cpu: "500m"
      limits:
        memory: "2.5Gi"
        cpu: "1000m"

identity:
  enabled: true
  firstUser:
    enabled: true
    username: demo
    email: demo@example.org
    firstName: Demo
    lastName: User
    secret:
      inlineSecret: "demo"

identityKeycloak:
  enabled: true
  auth:
    adminPassword: "${KC_ADMIN_PASS}"
    managementPassword: "${KC_ADMIN_PASS}"

optimize:
  enabled: false
webModeler:
  enabled: false
console:
  enabled: false
HELMEOF

info "Written to $DEPLOY_DIR/values-camunda.yaml"

# ── Pre-create camunda-credentials secret ─────────────────────────────────────
# The Helm chart references this secret but does NOT create it automatically
# when using identityKeycloak.auth.adminPassword (inline value).
# Without this, Identity and PostgreSQL pods fail with "secret not found".
step "Pre-creating camunda-credentials secret"
kubectl create secret generic camunda-credentials \
    --from-literal=identity-keycloak-admin-password="${KC_ADMIN_PASS}" \
    --from-literal=identity-keycloak-management-password="${KC_ADMIN_PASS}" \
    --from-literal=identity-keycloak-postgresql-user-password="${PG_PASS}" \
    --from-literal=identity-keycloak-postgresql-admin-password="${KC_ADMIN_PASS}" \
    --from-literal=postgresql-password="${PG_PASS}" \
    -n camunda --dry-run=client -o yaml | kubectl apply -f -
info "Done"

# ── Install Camunda ───────────────────────────────────────────────────────────
step "Camunda install (~15-20 min)"
helm upgrade --install camunda camunda/camunda-platform \
    -f "$DEPLOY_DIR/values-camunda.yaml" \
    -n camunda \
    --timeout 25m

info "Waiting for all pods (~15 min)..."
kubectl wait --for=condition=Ready pod \
    -l app.kubernetes.io/instance=camunda \
    -n camunda \
    --timeout=1200s

# ── Fix browser redirect URLs ─────────────────────────────────────────────────
# After install we know the actual LoadBalancer nodePort.
# Set publicIssuerUrl + orchestration.redirectUrl so Keycloak redirects
# point to the real server IP:port instead of localhost:8080.
step "Configuring external URLs for browser access"
HTTP_PORT=$(kubectl get svc camunda-zeebe-gateway -n camunda \
    -o jsonpath="{.spec.ports[?(@.name=='http')].nodePort}" 2>/dev/null)

if [[ -z "$HTTP_PORT" ]]; then
    warn "Could not detect HTTP nodePort — using default 8080"
    HTTP_PORT=8080
fi

PUBLIC_URL="http://${SERVER_IP}:${HTTP_PORT}"

python3 - << PYEOF
import yaml, sys

with open("${DEPLOY_DIR}/values-camunda.yaml") as f:
    d = yaml.safe_load(f)

pub = "${PUBLIC_URL}"

# Browser-facing Keycloak issuer URL
d.setdefault("global", {}).setdefault("identity", {}).setdefault("auth", {})
d["global"]["identity"]["auth"]["publicIssuerUrl"] = pub + "/auth/realms/camunda-platform"

# Auth URL for the browser-facing login page
d["global"]["identity"]["auth"]["authUrl"] = pub + "/auth/realms/camunda-platform/protocol/openid-connect/auth"

# sso-callback URL — must match what Zeebe/Operate serve
d.setdefault("orchestration", {}).setdefault("security", {}).setdefault("authentication", {}).setdefault("oidc", {})
d["orchestration"]["security"]["authentication"]["oidc"]["redirectUrl"] = pub

with open("${DEPLOY_DIR}/values-camunda.yaml", "w") as f:
    yaml.dump(d, f, default_flow_style=False)

print("Set publicIssuerUrl and redirectUrl to:", pub)
PYEOF

helm upgrade camunda camunda/camunda-platform \
    -f "$DEPLOY_DIR/values-camunda.yaml" \
    -n camunda \
    --timeout 10m

info "Waiting for pods after URL config..."
sleep 30
kubectl wait --for=condition=Ready pod \
    -l app.kubernetes.io/instance=camunda \
    -n camunda \
    --timeout=300s

# ── Done ──────────────────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}  Camunda 8 is live!${NC}"
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo "  Operate:   ${PUBLIC_URL}/operate"
echo "  Tasklist:  ${PUBLIC_URL}/tasklist"
echo "  Identity:  ${PUBLIC_URL}/identity"
echo "  Zeebe:     ${PUBLIC_URL}"
echo ""
echo "  Login: demo / demo"
echo "  (redirects to Keycloak — auth is via ${PUBLIC_URL}/auth)"
echo ""
echo "  Configs: ${DEPLOY_DIR}/"
